[package]
name = "goadder"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]


[dependencies]
uniffi = { version = "0.23" }

[build-dependencies]
uniffi = { version = "0.23", features = ["build"] }
